### ISSUE TITLE
Autoloads for all casual entry points

### ISSUE THREAD

**Issue by pkryger** [kickingvegas/casual#100]
If one uses a configuration where loading of `casual` is deferred (i.e., no `(require 'casual)`) then entry points that don't have autoloads cannot be used. For example, when using `dired` one cannot use `casual-dired-sort-by-tmenu` (which may be bounded to say <kbd>s</kbd>). One would have to use `casual-dired-tmenu` first. As a workaround I create required autoloads with `use-package`, as described in https://github.com/kickingvegas/casual/discussions/60#discussioncomment-11461674

Could it be possible to add `###autoload` cookies to the following functions? I can cut a PR if convenient.

* casual-dired
  * casual-dired-sort-by-tmenu
   * casual-dired-search-replace-tmenu
* casual-ibuffer
  * casual-ibuffer-filter-tmenu
  * casual-ibuffer-sortby-tmenu
* casual-i search
  * casual-isearch-tmenu

**Comment by kickingvegas** [comment]
Thanks for sharing this. Upon reflection, I’m thinking all `*-tmenu` declarations should be autoloaded. Will add this to the next release.

**Comment by kickingvegas** [comment]
Changed mind, only autoloading a subset of all tmenu declarations, in this case some EditKit menus. 

List of autoloaded tmenu declarations are in the PR commit #105.

**Comment by pkryger** [comment]
Thank you! These definitely cover the set I am intending to use.
