### ISSUE TITLE
How to change C-o default key

### ISSUE THREAD

**Issue by OrionRandD** [kickingvegas/casual#119]
Hi,
My StumpWM default key is exactly C-o
https://github.com/stumpwm/stumpwm
So that, how do I change your casual package C-o
to another keybinding not to clash with my WM?
Thx

**Comment by kickingvegas** [comment]
@OrionRandD You are free to choose a different binding. There is no requirement that it be C-o, it is just a suggestion/preference of mine.

**Comment by OrionRandD** [comment]
> Hi, My StumpWM default key is exactly C-o https://github.com/stumpwm/stumpwm So that, how do I change your casual package C-o to another keybinding not to clash with my WM? Thx

;;;;;;;;;;;;;;;;;;;;;;;;;

Never mind, I've found how to do it, using the casual-suite configuration...
