### ISSUE TITLE
Upgrade won't delete some packages

### ISSUE THREAD

**Issue by artelse** [kickingvegas/casual#43]
When I run `casual-upgrade-base-to-version-2`, package `casual-lib` and `casual-symbol-overlay` are not deleted. I saw you have removed the `use-package` configuration options. Indeed there is a problem the packages will be downloaded and installed again on a restart. Does this has to do how packages are now being declared and `use-package` is not aware?
Anyway going through the motions reconfiging.

**Comment by kickingvegas** [comment]
If you are using `use-package`, make sure that you have `:ensure nil` set to avoid re-installation of that package.

Also it might be best if you explicitly delete `casual-lib` and `casual-symbol-overlay` from the package manager. You can re-install `casual-symbol-overlay` afterwards.

**Comment by kickingvegas** [comment]
Another command you should run too is `package-autoremove` to remove all dependent packages that are unused.

**Comment by kickingvegas** [comment]
Any updates?

**Comment by artelse** [comment]
Just a quick response, came home from meetings. `package-autoremove` actually deleted `casual`. I didn't have any casual packages configured, so that might made sense. `:ensure nil` doesn't load the package of course, so the `:bind` keybindings also don't work. I now just have to make a keybinding to launch the required casual tmenu.  A pity I cannot use `use-package` for configuration, just a preference for consistency in my config.

**Comment by kickingvegas** [comment]
@artelse out of curiosity are you using `use-package` to install and not the [package menu buffer](https://www.gnu.org/software/emacs/manual/html_node/emacs/Package-Menu.html)?

If so then that would likely explain why `casual` was removed by `package-autoremove`.

I cannot vet this answer but this may perhaps lead you to the right direction on using `use-package` to configure `casual`.

https://www.reddit.com/r/emacs/comments/1g990g9/comment/lt7o6ok/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by kickingvegas** [comment]
Also I'd add that there is no prohibition on using `use-package` with Casual. It is just that I am not qualified to give good guidance on it. So I have stopped trying.

Thanks all the same for sharing your experience.

**Comment by artelse** [comment]
One more thing. I now config through the keymap settings. All work fine, only `casual-calc` needs an explicit `(require 'casual-calc)` the others work just fine without.
I will check the reddit post later. Thanks for the great casual package!
Edit: had a quick look at that reddit post. Interesting idea to use `use-package` in the `:init` of `casual` Will test later.
