### ISSUE TITLE
Difficulty in setting keybindings for casual-calc via use-package

### ISSUE THREAD

**Issue by TriAttack238** [kickingvegas/casual#59]
I've managed to install the new casual package with elpaca and use-package, but the keybinding remapping is not going well. This is the relevant code in my init.el:

```
(use-package casual
  :ensure t
  :defer t
  )

;; Casual Calc Keymap

(keymap-set calc-mode-map "C-o" #'casual-calc-tmenu)
(keymap-set calc-alg-map "C-o" #'casual-calc-tmenu)
```
However, opening calc and using C-o does not work, instead during init it causes this error: 
```
Debugger entered--Lisp error: (void-variable calc-mode-map)
  (keymap-set calc-mode-map "C-o" #'casual-calc-tmenu)
  load-with-code-conversion("c:/Users/user/.emacs.d/init.el" "c:/Users/user/.emacs.d/init.el" t t)
  load("c:/Users/user/.emacs.d/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode -0x1c6cfd57de8fc2b6>) #f(compiled-function () #<bytecode -0x1f3c61addc0c4f35>) t)
  command-line()
  normal-top-level()
```
Additionally, if I `(require 'casual-calc)` emacs cannot find the package. What am I doing wrong here?

**Comment by TriAttack238** [comment]
Ok, it turns out you have to `require calc` instead. Or use a use-package declaration similar to this one I have:
```
;; Casual Calc Keymap
(use-package calc
  :ensure nil
  :bind (
	 :map calc-mode-map
	      ("C-o" . casual-calc-tmenu)
	 :map calc-alg-map
	      ("C-o" . casual-calc-tmenu)
	 )
  :defer t)
```

**Comment by TriAttack238** [comment]
Correction, there is indeed a problem. The mapping of `calc-alg-map` lead to beign unable to open calc. This is because of an error saying "if: Symbol’s value as variable is void: calc-alg-map". I am not sure what the cause of this is.

**Comment by kickingvegas** [comment]
@TriAttack238 `calc-alg-map` is defined in `calc-ext` so I suspect that you'll need to get `use-package` to import it accordingly. 

As I've mentioned in the Casual 2.0 documentation, I no longer provide guidance in using `use-package` for Casual as I am not experienced enough with it.

**Comment by TriAttack238** [comment]
Ah, I was invoking the wrong package. Let me try that.

**Comment by TriAttack238** [comment]
Ok, I now have use-package declarations that work for all of the libraries in this package(Calc, dired, info, bookmark, ibuffer). Will consider sending a pull request to change documentation.

**Comment by kickingvegas** [comment]
@TriAttack238 please instead of a pull request, create a discussion item that details your usage of `use-package`. That way this configuration can be collectively reviewed. If this or some variant of it is deemed reliable then I will consider providing `use-package` support back into the Casual documentation.
